parameters:

#Crop params
#     *      exact = The exact height and width dimensions you set. (Default)
#     *      portrait = Whatever height is passed in will be the height that
#     *          is set. The width will be calculated and set automatically
#     *          to a the value that keeps the original aspect ratio.
#     *      landscape = The same but based on the width. We try make the image
#     *         the biggest size we can while stil fitting inside the box size
#     *      auto = Depending whether the image is landscape or portrait, this
#     *          will automatically determine whether to resize via
#     *          dimension 1,2 or 0
#     *      crop = Will resize and then crop the image for best fit

services:
    file_upload.handler:
        class: Voltash\UploadBundle\Services\FileHandler
        arguments: [@session, %file_upload.types%]
